export const metadata = {
   title: "Contact Next App",
   description: "Generated by create next app",
};

const contact = () => {
   return (
      <div>
         <h1>this is the contact page.</h1>
         <h1>this is the contact page.</h1>
      </div>
   );
};

export default contact;
