export const metadata = {
   title: "Add Product Next App",
   description: "Generated by create next app",
};
const page = () => {
   return (
      <div>
         <h1> this is the add Product page</h1>
      </div>
   );
};

export default page;
