export const metadata = {
   title: "about | Next App",
   description: "Generated by create next app",
};

const page = () => {
   return (
      <div>
         <h1>This is the about page.</h1>
      </div>
   );
};

export default page;
