import Sidebar from "./Sidebar";

export const metadata = {
   title: "Dashboard Next App",
   description: "Generated by create next app",
};

const DashboardLayout = ({ children }) => {
   return (
      <div>
         <Sidebar />
         {children}
      </div>
   );
};

export default DashboardLayout;
