export const metadata = {
   title: "Dashboard Next App",
   description: "Generated by create next app",
};
const dashboard = () => {
   return (
      <div>
         <h1>This is the dashboard page.</h1>
         <h1>e.</h1>
      </div>
   );
};

export default dashboard;
